# version: '3.8'

services:
  movies:
    build: ./TestDrivenIO
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./TestDrivenIO/:/usr/src/TestDrivenIO/
    ports:
      - 8009:8000
    env_file:
      - ./TestDrivenIO/.env.dev