# version: '3.8'

services:
  movies:
    build: ./TestDrivenIO
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./TestDrivenIO/:/usr/src/TestDrivenIO/
    ports:
      - 8009:8000
    env_file:
      - ./TestDrivenIO/.env.dev
    depends_on:
      - movies-db
  movies-db:
    image: postgres:15
    volumes:  # create a volume and bind directory to the container
      - postgres_data:/var/lib/postgresql/data/
    environment:  # added ENV key to define a name for default DB & credentials
      - POSTGRES_USER=movies
      - POSTGRES_PASSWORD=movies
      - POSTGRES_DB=movies_dev

volumes:
  postgres_data: